### ISSUE TITLE
Allow passing of parameters to include

### ISSUE THREAD

**Issue by sirlantis** [docs/liquid#37]
Newer versions of liquid allow the `include` tag to pass values. Current workaround is:

```
{% assign snippet_variable = 'this is it' %}
{% assign snippet_variable_two = 'this is also it' %}
{% include 'snippet' %}
```

**Comment by Lewiscowles1986** [comment]
seems good to close? it's a little confusing what if anything is left to do

**Comment by GustavoRPS** [comment]
Has variable support been included?

**Comment by zeke** [comment]
@GustavoRPS I'm not sure. There's a chance it's supported but not documented. Feel free to dig in and report your findings.

**Comment by pburrows** [comment]
I can't currently even get the `{% assign snippet_variable = 'this is it' %}` work around working. Has this functionality broken for an include tag (I don't see a unit test that covers this, so it may have?)

**Comment by JasonEtco** [comment]
Noting here that Shopify Liquid has since added a `{% render %}` tag, which is like `include` but _does not_ share the parent context to the included snippet, and allows for setting variables. [Docs here](https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags#render), working on implementation in this repo in #114
